name: Ruby CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests and lint
      run: bundle exec rake
    - name: Build gem
      run: gem build echonet_lite_gem.gemspec
    - name: Install built gem
      run: gem install ./echonet_lite_gem-*.gem --local